version: '3.8'

services:
  mysql:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
    ports:
      - "3306:3306"

  app:
    build:
      context: ./app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ScripsecurityWings
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: urubu100
    ports:
      - "8080:8080"
