
# Comando que instala o Javazin
FROM openjdk:17-jdk-slim

WORKDIR /app

COPY seu-aplicativo.jar /app/seu-aplicativo.jar

# Comando para executar o Jar
CMD ["java", "-jar", "\app\Java-Wings-Squad\out\artifacts\Security_Wings_Looca_jar\Security-Wings-Looca.jar"]
